git subrepo pull src/liblouis
subrepo:
  subdir:   "src/liblouis"
  merged:   "8a0e5e4c"
upstream:
  origin:   "git@github.com:liblouis/liblouis.git"
  branch:   "master"
  commit:   "d6daa923"
git-subrepo:
  version:  "0.3.1"
  origin:   "???"
  commit:   "???"

diff --git a/src/liblouis/.github/workflows/mingw.yml b/src/liblouis/.github/workflows/mingw.yml
--- a/src/liblouis/.github/workflows/mingw.yml
+++ b/src/liblouis/.github/workflows/mingw.yml
@@ -4,11 +4,16 @@ on:
   workflow_dispatch:
   push:
     branches: [ master ]
-    paths-ignore:
-      - README
-      - NEWS
+    paths:
+      - '**.h'
+      - '**.c'
+      - 'liblouis/liblouis/liblouis.h.in'
   pull_request:
     branches: [ master ]
+    paths:
+      - '**.h'
+      - '**.c'
+      - 'liblouis/liblouis/liblouis.h.in'
 
 env:
   LIBYAML_VERSION: 0.1.4
@@ -23,9 +28,14 @@ jobs:
       PREFIX: /tmp/build/win64
 
     steps:
-    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
+    - name: Harden Runner
+      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
+      with:
+        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
+
+    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
     - name: Install dependencies
-      run: sudo apt-get update -qq && sudo apt-get install -y autoconf automake curl libtool make mingw-w64 pkg-config texinfo wine64 zip patch
+      run: sudo apt-get update -qq && sudo apt-get install -y autoconf automake curl libtool make mingw-w64 pkg-config texinfo wine64 zip patch jq
     - name: Build libyaml
       run: |
         curl -L https://github.com/yaml/libyaml/archive/${{ env.LIBYAML_VERSION }}.tar.gz | tar zx
@@ -45,7 +55,7 @@ jobs:
       run: make check WINE=wine64
     - name: Store the test suite log
       if: ${{ failure() }}
-      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
+      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
       with:
         name: test-suite-w64.log
         path: tests/test-suite.log
@@ -55,7 +65,7 @@ jobs:
     - name: Zip up the build artifacts
       run: ( cd ${{ env.PREFIX }}; zip -r liblouis.zip * )
     - name: Archive the build artifacts
-      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
+      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
       with:
         name: liblouis-w64.zip
         path:  ${{ env.PREFIX }}/liblouis.zip
@@ -63,7 +73,7 @@ jobs:
     - name: Upload the assets to the snapshot release
       # only upload to snapshot page if it is a push to master in the main repo
       if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository =='liblouis/liblouis'}}
-      uses: shogo82148/actions-upload-release-asset@e94a7386c3c266a207386460471b1efb5c7431eb # v1.6.3
+      uses: shogo82148/actions-upload-release-asset@953d19cc84d8e8ecf80beec5afef40ca68b7e633 # v1.6.6
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         upload_url: https://uploads.github.com/repos/liblouis/liblouis/releases/8031256/assets{?name,label}
@@ -72,67 +82,91 @@ jobs:
         asset_content_type: application/zip
         overwrite: true
 
-  build-w32:
-    name: Build for win32
-
-    runs-on: ubuntu-latest
-    env:
-      HOST: i686-w64-mingw32
-      PREFIX: /tmp/build/win32
-
-    steps:
-    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
-    - name: Install dependencies
-      run: sudo apt-get update -qq && sudo apt-get install -y autoconf automake curl libtool make pkg-config texinfo zip patch
-    - name: Install wine for 32-bit architecture
-      run: |
-        sudo apt-get update -qq
-        sudo dpkg --add-architecture i386
-        sudo apt-get update
-        sudo apt-get install -y fonts-wine libc6-dev-i386-x32-cross mingw-w64 mingw-w64-i686-dev wine-development wine32 # FIXME: in 20.4 wine-development will be just wine
-
-    - name: Build libyaml
-      run: |
-        curl -L https://github.com/yaml/libyaml/archive/${{ env.LIBYAML_VERSION }}.tar.gz | tar zx
-        cd libyaml-${{ env.LIBYAML_VERSION }}
-        patch -p1 < ../libyaml_mingw.patch
-        ./bootstrap
-        ./configure --host ${{ env.HOST }} --prefix=${{ env.PREFIX }}
-        make
-        make install
-    - name: Autogen && configure
-      run: |
-        ./autogen.sh
-        ./configure --host ${{ env.HOST }} --enable-ucs4 --prefix=${{ env.PREFIX }} CFLAGS="-O0" CPPFLAGS="-I${{ env.PREFIX }}/include/" LDFLAGS="-L${{ env.PREFIX }}/lib/" 
-    - name: Make
-      run: make LDFLAGS="-L${{ env.PREFIX }}/lib/ -avoid-version -Xcompiler -static-libgcc"
-    - name: Check
-      run: make check WINE=wine
-    - name: Store the test suite log
-      if: ${{ failure() }}
-      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
-      with:
-        name: test-suite-w32.log
-        path: tests/test-suite.log
-    - name: Install
-      run: make install
-
-    - name: Zip up the build artifacts
-      run: ( cd ${{ env.PREFIX }}; zip -r liblouis.zip * )
-    - name: Archive the build artifacts
-      uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
-      with:
-        name: liblouis-w32.zip
-        path:  ${{ env.PREFIX }}/liblouis.zip
-
-    - name: Upload the assets to the snapshot release
-      # only upload to snapshot page if it is a push to master in the main repo
+    - name: Edit the description of the snapshot release
       if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository =='liblouis/liblouis'}}
-      uses: shogo82148/actions-upload-release-asset@e94a7386c3c266a207386460471b1efb5c7431eb # v1.6.3
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        upload_url: https://uploads.github.com/repos/liblouis/liblouis/releases/8031256/assets{?name,label}
-        asset_path: ${{ env.PREFIX }}/liblouis.zip
-        asset_name: liblouis-w32.zip
-        asset_content_type: application/zip
-        overwrite: true
+      run: |
+        if ! curl -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"            \
+                  -H "Accept: application/json"                                     \
+                  -H "Content-type: application/json"                               \
+                  -X PATCH                                                          \
+                  "https://api.github.com/repos/liblouis/liblouis/releases/8031256" \
+                  -d "{\"tag_name\": \"snapshot\",                                  \
+                       \"body\":     \"Latest build: ${{ github.sha }}\"}"          \
+                  2>/dev/null                                                       \
+             | jq -e '.url';                                                        \
+        then                                                                        \
+            echo "Failed to edit release description" &&                            \
+            exit 1;                                                                 \
+        fi
+
+  # win32 build disabled for now: see https://github.com/liblouis/liblouis/issues/1135
+
+  #build-w32:
+  #  name: Build for win32
+  #
+  #  runs-on: ubuntu-latest
+  #  env:
+  #    HOST: i686-w64-mingw32
+  #    PREFIX: /tmp/build/win32
+  #
+  #  steps:
+  #  - name: Harden Runner
+  #    uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
+  #    with:
+  #      egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs
+  #
+  #  - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+  #  - name: Install dependencies
+  #    run: sudo apt-get update -qq && sudo apt-get install -y autoconf automake curl libtool make pkg-config texinfo zip patch
+  #  - name: Install wine for 32-bit architecture
+  #    run: |
+  #      sudo apt-get update -qq
+  #      sudo dpkg --add-architecture i386
+  #      sudo apt-get update
+  #      sudo apt-get install -y fonts-wine libc6-dev-i386-x32-cross mingw-w64 mingw-w64-i686-dev wine-development wine32 # FIXME: in 20.4 wine-development will be just wine
+  #
+  #  - name: Build libyaml
+  #    run: |
+  #      curl -L https://github.com/yaml/libyaml/archive/${{ env.LIBYAML_VERSION }}.tar.gz | tar zx
+  #      cd libyaml-${{ env.LIBYAML_VERSION }}
+  #      patch -p1 < ../libyaml_mingw.patch
+  #      ./bootstrap
+  #      ./configure --host ${{ env.HOST }} --prefix=${{ env.PREFIX }}
+  #      make
+  #      make install
+  #  - name: Autogen && configure
+  #    run: |
+  #      ./autogen.sh
+  #      ./configure --host ${{ env.HOST }} --enable-ucs4 --prefix=${{ env.PREFIX }} CFLAGS="-O0" CPPFLAGS="-I${{ env.PREFIX }}/include/" LDFLAGS="-L${{ env.PREFIX }}/lib/" 
+  #  - name: Make
+  #    run: make LDFLAGS="-L${{ env.PREFIX }}/lib/ -avoid-version -Xcompiler -static-libgcc"
+  #  - name: Check
+  #    run: make check WINE=wine
+  #  - name: Store the test suite log
+  #    if: ${{ failure() }}
+  #    uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
+  #    with:
+  #      name: test-suite-w32.log
+  #      path: tests/test-suite.log
+  #  - name: Install
+  #    run: make install
+  #
+  #  - name: Zip up the build artifacts
+  #    run: ( cd ${{ env.PREFIX }}; zip -r liblouis.zip * )
+  #  - name: Archive the build artifacts
+  #    uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
+  #    with:
+  #      name: liblouis-w32.zip
+  #      path:  ${{ env.PREFIX }}/liblouis.zip
+  #
+  #  - name: Upload the assets to the snapshot release
+  #    # only upload to snapshot page if it is a push to master in the main repo
+  #    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository =='liblouis/liblouis'}}
+  #    uses: shogo82148/actions-upload-release-asset@953d19cc84d8e8ecf80beec5afef40ca68b7e633 # v1.6.6
+  #    with:
+  #      github_token: ${{ secrets.GITHUB_TOKEN }}
+  #      upload_url: https://uploads.github.com/repos/liblouis/liblouis/releases/8031256/assets{?name,label}
+  #      asset_path: ${{ env.PREFIX }}/liblouis.zip
+  #      asset_name: liblouis-w32.zip
+  #      asset_content_type: application/zip
+  #      overwrite: true
